# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BZQzpLW5w3ACYGD4CtKZ3iXPNL-7j-Ak

## Imports
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ks_2samp

"""# Funções"""

def calculate_psi(expected, actual, bins=10):
    expected, bins = np.histogram(expected, bins=bins, density=True)
    actual, _ = np.histogram(actual, bins=bins, density=True)

    expected = np.clip(expected, 1e-10, None)
    actual = np.clip(actual, 1e-10, None)

    psi_values = (expected - actual) * np.log(expected / actual)
    return np.sum(psi_values.round(4)*100)

def calculate_ks(y_true, y_pred_prob):
    y_pred_0 = y_pred_prob[y_true == 0]
    y_pred_1 = y_pred_prob[y_true == 1]
    ks_stat, _ = ks_2samp(y_pred_0, y_pred_1)
    return ks_stat

